title: Muzammil Jawed # your name (or website title) here
logo: <img src="/images/headshot.jpeg?raw=true" width="400"/>
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://www.linkedin.com/in/muzammil-jawed/">LinkedIn</a> 
  <br>
  <a href="https://www.GitHub.com/muj225/">GitHub</a>  
  <br>
  <a href="https://www.researchgate.net/profile/Muzammil-Jawed">ResearchGate</a> 

  
theme: jekyll-theme-minimal
